# Generated by Django 5.2.4 on 2026-04-29 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(max_length=10, unique=True)),
                ('qr_code_token', models.CharField(blank=True, max_length=100, unique=True)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['table_number'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(default='Gourmet House', max_length=200)),
                ('restaurant_phone', models.CharField(default='+250 788 123 456', max_length=20)),
                ('restaurant_email', models.EmailField(default='info@gourmethouse.com', max_length=254)),
                ('restaurant_address', models.TextField(default='123 Restaurant Ave, Kigali')),
                ('currency_symbol', models.CharField(default='$', max_length=5)),
                ('currency_code', models.CharField(default='USD', max_length=10)),
                ('enable_delivery', models.BooleanField(default=True, help_text='Enable delivery service')),
                ('delivery_radius_km', models.PositiveIntegerField(default=10, help_text='Maximum delivery distance in kilometers')),
                ('min_order_for_delivery', models.DecimalField(decimal_places=2, default=0, help_text='Minimum order amount for delivery', max_digits=10)),
                ('delivery_fee_type', models.CharField(choices=[('fixed', 'Fixed Fee'), ('distance', 'Distance Based'), ('percentage', 'Percentage of Order')], default='fixed', max_length=20)),
                ('delivery_fee_amount', models.DecimalField(decimal_places=2, default=3.0, help_text='Fixed delivery fee', max_digits=10)),
                ('delivery_fee_percentage', models.DecimalField(decimal_places=2, default=10, help_text='Percentage of order for delivery fee', max_digits=5)),
                ('delivery_fee_per_km', models.DecimalField(decimal_places=2, default=0.5, help_text='Fee per kilometer', max_digits=5)),
                ('free_delivery_minimum', models.DecimalField(decimal_places=2, default=50, help_text='Minimum order for free delivery', max_digits=10)),
                ('estimated_delivery_time', models.CharField(default='30-45 minutes', max_length=100)),
                ('enable_card_payment', models.BooleanField(default=True)),
                ('enable_mobile_money', models.BooleanField(default=True)),
                ('enable_cash_on_delivery', models.BooleanField(default=True)),
                ('enable_cash_dine_in', models.BooleanField(default=True)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, help_text='Tax percentage', max_digits=5)),
                ('service_charge', models.DecimalField(decimal_places=2, default=0, help_text='Service charge percentage', max_digits=5)),
                ('enable_tips', models.BooleanField(default=True)),
                ('tip_distribution_method', models.CharField(choices=[('waiter_keeps', 'Waiter Keeps Their Tips'), ('pooled', 'Pooled & Shared Among All Staff'), ('manager_decides', 'Manager Decides Distribution')], default='waiter_keeps', max_length=30)),
                ('suggested_tip_percentages', models.JSONField(default=list, help_text='Suggested tip percentages e.g., [10, 15, 18, 20]')),
                ('opening_time', models.TimeField(default='09:00')),
                ('closing_time', models.TimeField(default='22:00')),
                ('is_open_sunday', models.BooleanField(default=True)),
                ('is_open_monday', models.BooleanField(default=True)),
                ('is_open_tuesday', models.BooleanField(default=True)),
                ('is_open_wednesday', models.BooleanField(default=True)),
                ('is_open_thursday', models.BooleanField(default=True)),
                ('is_open_friday', models.BooleanField(default=True)),
                ('is_open_saturday', models.BooleanField(default=True)),
                ('qr_code_size', models.IntegerField(default=200, help_text='QR code size in pixels')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Restaurant Setting',
                'verbose_name_plural': 'Restaurant Settings',
            },
        ),
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line', models.TextField()),
                ('house_number', models.CharField(blank=True, max_length=50)),
                ('apartment', models.CharField(blank=True, max_length=50)),
                ('landmark', models.CharField(blank=True, max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(choices=[('motorcycle', 'Motorcycle'), ('car', 'Car'), ('bicycle', 'Bicycle')], default='motorcycle', max_length=50)),
                ('license_plate', models.CharField(blank=True, max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('busy', 'On Delivery'), ('offline', 'Offline')], default='available', max_length=20)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('total_deliveries', models.IntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
