# Generated by Django 5.2.4 on 2025-08-02 22:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_table_alter_cartitem_unique_together_reservation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['-added_at']},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': 'Inventory'},
        ),
        migrations.AlterModelOptions(
            name='menucategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Menu Categories'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Order Item', 'verbose_name_plural': 'Order Items'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['number']},
        ),
        migrations.AddField(
            model_name='menuitem',
            name='order_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='received', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.TimeField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='restaurant__status_bb9ec8_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['date', 'time'], name='restaurant__date_9c0bc5_idx'),
        ),
    ]
