# Generated by Django 5.2.4 on 2025-08-03 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_cartitem_options_alter_inventory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='order_count',
        ),
    ]
