# Generated by Django 5.2.4 on 2026-05-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_order_confirmed_at_order_rejection_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='is_available',
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicle_type',
            field=models.CharField(choices=[('motorcycle', 'Motorcycle'), ('car', 'Car'), ('bicycle', 'Bicycle')], default='motorcycle', max_length=20),
        ),
    ]
