# Generated by Django 5.2.4 on 2026-02-20 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_order_payment_method_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(blank=True, help_text='Required for non-logged-in users', max_length=254, null=True),
        ),
    ]
