# Generated by Django 5.2.4 on 2026-02-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_reservation_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5, help_text='Alert when stock falls below this number'),
        ),
    ]
